package br.com.stefanini.hackathon.util;

import br.com.stefanini.hackathon.model.Candidato;

import java.util.ArrayList;
import java.util.List;

public class VetorUtil {
    public List<Candidato> lista = new ArrayList<Candidato>();

    public VetorUtil() {
        lista.add(new Candidato("Lucas", "Aracaju", 99));
        lista.add(new Candidato("Mateus", "Aracaju", 99));
        lista.add(new Candidato("Maria", "Aracaju", 99));
        lista.add(new Candidato("Raimunda", "Socorro", 99));
        lista.add(new Candidato("Leonardo", "Dores", 99));
        lista.add(new Candidato("Odete", "Aparecida", 99));
        lista.add(new Candidato("Safira", "Aparecida", 99));
        lista.add(new Candidato("Jurema", "Aparecida", 99));
        lista.add(new Candidato("Teo", "Aparecida", 99));
        lista.add(new Candidato("Luca", "Glória", 99));
        lista.add(new Candidato("Gertrudes", "Pindamonhagaba", 99));
        lista.add(new Candidato("Gervasio", "Caruaru", 99));
        lista.add(new Candidato("Celene", "Tomar do Geru", 99));
        lista.add(new Candidato("Carla", "Estância", 99));
        lista.add(new Candidato("Simone", "Glória", 99));
        lista.add(new Candidato("Pablo", "Malhador", 99));
        lista.add(new Candidato("Tristan", "Malhador", 99));
        lista.add(new Candidato("Tairyne", "Malhada dos Bois", 99));
        lista.add(new Candidato("Leandra", "Caninde", 99));
        lista.add(new Candidato("Hunter", "Blevio", 63));
        lista.add(new Candidato("Judah", "Sint-Stevens-Woluwe", 31));
        lista.add(new Candidato("Malik", "Quebec City", 60));
        lista.add(new Candidato("Zeus", "Valcourt", 67));
        lista.add(new Candidato("Patrick", "Bekegem", 82));
        lista.add(new Candidato("Shannon", "Salamanca", 98));
        lista.add(new Candidato("Fiona", "Guaitecas", 95));
        lista.add(new Candidato("Susan", "Leduc", 40));
        lista.add(new Candidato("Joshua", "Shebekino", 83));
        lista.add(new Candidato("Amena", "Rouyn-Noranda", 74));
        lista.add(new Candidato("Quemby", "Ross-on-Wye", 8));
        lista.add(new Candidato("Alexis", "Dieppe", 72));
        lista.add(new Candidato("Chester", "Paal", 87));
        lista.add(new Candidato("Mia", "Kearney", 68));
        lista.add(new Candidato("Maryam", "Eigenbrakel", 98));
        lista.add(new Candidato("Veda", "Salem", 83));
        lista.add(new Candidato("Zephr", "Silifke", 45));
        lista.add(new Candidato("Joshua", "Newmarket", 20));
        lista.add(new Candidato("Kirby", "Kolhapur", 59));
        lista.add(new Candidato("Simon", "Burntisland", 58));
        lista.add(new Candidato("Clinton", "Paulista", 17));
        lista.add(new Candidato("Quentin", "Chilpancingo", 89));
        lista.add(new Candidato("Avye", "Melville", 48));
        lista.add(new Candidato("Illiana", "Belford Roxo", 10));
        lista.add(new Candidato("Samuel", "Neubrandenburg", 81));
        lista.add(new Candidato("Akeem", "Göttingen", 56));
        lista.add(new Candidato("Quinn", "Sedgewick", 74));
        lista.add(new Candidato("Grace", "Épernay", 95));
        lista.add(new Candidato("Erich", "Arequipa", 6));
        lista.add(new Candidato("Tashya", "Lutterworth", 36));
        lista.add(new Candidato("Beatrice", "Bevilacqua", 6));
        lista.add(new Candidato("Justin", "Lasbela", 92));
        lista.add(new Candidato("Christopher", "Paupisi", 68));
        lista.add(new Candidato("Victoria", "Aalst", 37));
        lista.add(new Candidato("Adara", "Ramenskoye", 85));
        lista.add(new Candidato("Ivor", "Stony Plain", 59));
        lista.add(new Candidato("Cecilia", "Akşehir", 47));
        lista.add(new Candidato("Jerry", "Nanaimo", 95));
        lista.add(new Candidato("MacKenzie", "Medellín", 6));
        lista.add(new Candidato("Latifah", "Lo Prado", 95));
        lista.add(new Candidato("Ray", "Heist-aan-Zee", 91));
        lista.add(new Candidato("Reed", "Maranello", 89));
        lista.add(new Candidato("Nichole", "Miami", 22));
        lista.add(new Candidato("Georgia", "Denver", 84));
        lista.add(new Candidato("Jordan", "Saint Paul", 0));
        lista.add(new Candidato("Isabelle", "Paine", 79));
        lista.add(new Candidato("Orlando", "Medemblik", 82));
        lista.add(new Candidato("Alfreda", "White Rock", 80));
        lista.add(new Candidato("Honorato", "Spaniard's Bay", 16));
        lista.add(new Candidato("Dara", "Ibadan", 80));
        lista.add(new Candidato("Velma", "San Benedetto del Tronto", 61));
        lista.add(new Candidato("Victor", "Filacciano", 20));
        lista.add(new Candidato("Howard", "Darlington", 66));
        lista.add(new Candidato("Alfonso", "Bruckneudorf", 22));
        lista.add(new Candidato("Irene", "Corroy-le-Ch‰teau", 89));
        lista.add(new Candidato("Beau", "Schellebelle", 55));
        lista.add(new Candidato("Liberty", "Rüsselsheim", 47));
        lista.add(new Candidato("Jemima", "Goutroux", 2));
        lista.add(new Candidato("Uriel", "Morpeth", 78));
        lista.add(new Candidato("Logan", "Moxhe", 99));
        lista.add(new Candidato("Thomas", "Opdorp", 71));
        lista.add(new Candidato("Beau", "Torre Cajetani", 92));
        lista.add(new Candidato("Kamal", "Hekelgem", 11));
        lista.add(new Candidato("Lester", "Coalhurst", 90));
        lista.add(new Candidato("Amery", "Camaragibe", 72));
        lista.add(new Candidato("Scott", "Westmalle", 42));
        lista.add(new Candidato("Asher", "Koningshooikt", 99));
        lista.add(new Candidato("Stacey", "Tollembeek", 85));
        lista.add(new Candidato("Samuel", "Sooke", 42));
        lista.add(new Candidato("Jin", "Sint-Michiels", 51));
        lista.add(new Candidato("Finn", "Townsville", 0));
        lista.add(new Candidato("Nero", "Massenhoven", 16));
        lista.add(new Candidato("Cain", "Ipswich", 79));
        lista.add(new Candidato("Kaseem", "Porvenir", 71));
        lista.add(new Candidato("Cassandra", "Gilly", 76));
        lista.add(new Candidato("Hu", "Kingston", 5));
        lista.add(new Candidato("Rebekah", "San Pablo", 34));
        lista.add(new Candidato("Merritt", "Duffel", 47));
        lista.add(new Candidato("Amy", "Vetlanda", 84));
        lista.add(new Candidato("Rashad", "Taupo", 45));
        lista.add(new Candidato("Anjolie", "Maranguape", 65));
        lista.add(new Candidato("Christen", "Gloucester", 36));
        lista.add(new Candidato("Hammett", "Te Puke", 43));
        lista.add(new Candidato("Lael", "Anchorage", 77));
        lista.add(new Candidato("Finn", "St. Albert", 99));
        lista.add(new Candidato("Ann", "Bosa", 83));
        lista.add(new Candidato("Amal", "Boneffe", 27));
        lista.add(new Candidato("Azalia", "Pogliano Milanese", 95));
        lista.add(new Candidato("Summer", "Cajazeiras", 18));
        lista.add(new Candidato("Calvin", "Saint-Honor", 76));
        lista.add(new Candidato("Arthur", "Flushing", 30));
        lista.add(new Candidato("Wayne", "Kalgoorlie-Boulder", 82));
        lista.add(new Candidato("Cassady", "Okigwe", 14));
        lista.add(new Candidato("Fay", "Macquenoise", 35));
        lista.add(new Candidato("Simone", "Okotoks", 39));
        lista.add(new Candidato("Blaze", "Outremont", 37));
        lista.add(new Candidato("Prescott", "Surrey", 10));
        lista.add(new Candidato("Aaron", "Ciudad Obregón", 61));
        lista.add(new Candidato("Gwendolyn", "Agra", 68));
        lista.add(new Candidato("Magee", "Warangal", 15));
        lista.add(new Candidato("Bo", "North Bay", 46));
        lista.add(new Candidato("Yoshio", "Lobnya", 57));
        lista.add(new Candidato("Judah", "Jodoigne", 55));
        lista.add(new Candidato("Brody", "Şereflikoçhisar", 29));
        lista.add(new Candidato("Rachel", "Chichester", 21));
        lista.add(new Candidato("Maya", "Cambridge Bay", 6));
        lista.add(new Candidato("Craig", "Chattanooga", 73));
        lista.add(new Candidato("Aspen", "Gonnosnò", 59));
        lista.add(new Candidato("Price", "Iqaluit", 44));
        lista.add(new Candidato("Brody", "Casper", 15));
        lista.add(new Candidato("Kalia", "Lakeshore", 62));
        lista.add(new Candidato("Vivien", "Alvito", 38));
        lista.add(new Candidato("Winifred", "Lodhran", 80));
        lista.add(new Candidato("Ava", "Polino", 73));
        lista.add(new Candidato("Sebastian", "Bhiwandi", 64));
        lista.add(new Candidato("Miriam", "Laino Castello", 87));
        lista.add(new Candidato("Daphne", "Cheonan", 15));
        lista.add(new Candidato("Blair", "Konya", 52));
        lista.add(new Candidato("Tucker", "Lienz", 14));
        lista.add(new Candidato("Deacon", "Enterprise", 42));
        lista.add(new Candidato("Buckminster", "Mariakerke", 70));
        lista.add(new Candidato("Macaulay", "Paiguano", 21));
        lista.add(new Candidato("Lucy", "Price", 31));
        lista.add(new Candidato("Judith", "Bevel", 60));
        lista.add(new Candidato("Yasir", "Noicattaro", 99));
        lista.add(new Candidato("Jennifer", "Devon", 6));
        lista.add(new Candidato("Hu", "Kleinmachnow", 90));
        lista.add(new Candidato("Kevin", "BiercŽe", 24));
        lista.add(new Candidato("Lynn", "Gilgit", 59));
        lista.add(new Candidato("Lee", "Craco", 33));
        lista.add(new Candidato("Bert", "Portico e San Benedetto", 78));
        lista.add(new Candidato("Eugenia", "Seilles", 71));
        lista.add(new Candidato("Courtney", "Kozhikode", 80));
        lista.add(new Candidato("Bethany", "Cañete", 68));
        lista.add(new Candidato("Zane", "Harderwijk", 90));
        lista.add(new Candidato("Nicole", "Lake Cowichan", 84));
        lista.add(new Candidato("Curran", "Solvychegodsk", 75));
        lista.add(new Candidato("Hashim", "Otegem", 34));
        lista.add(new Candidato("Lesley", "Rocky View", 0));
        lista.add(new Candidato("Haley", "Giarratana", 85));
        lista.add(new Candidato("Priscilla", "Ripalta Guerina", 10));
        lista.add(new Candidato("Thane", "Ravenstein", 86));
        lista.add(new Candidato("Zenia", "Ulm", 0));
        lista.add(new Candidato("Nicholas", "Meppel", 36));
        lista.add(new Candidato("Lynn", "Barahanagar", 41));
        lista.add(new Candidato("Berk", "Queilén", 1));
        lista.add(new Candidato("Nasim", "Villahermosa", 50));
        lista.add(new Candidato("Hadley", "Gubkin", 14));
        lista.add(new Candidato("Lee", "Estevan", 67));
        lista.add(new Candidato("Raven", "Bolzano Vicentino", 22));
        lista.add(new Candidato("Patrick", "Ely", 4));
        lista.add(new Candidato("Caesar", "Mala", 16));
        lista.add(new Candidato("Oscar", "Pazarcık", 59));
        lista.add(new Candidato("Nasim", "Naro", 3));
        lista.add(new Candidato("Rigel", "Depok", 74));
        lista.add(new Candidato("Honorato", "Saltcoats", 40));
        lista.add(new Candidato("September", "Cuxhaven", 16));
        lista.add(new Candidato("Jason", "Hohenems", 23));
        lista.add(new Candidato("Dante", "Vico del Gargano", 61));
        lista.add(new Candidato("Dahlia", "Yellowhead County", 55));
        lista.add(new Candidato("Maxine", "Kędzierzyn-Koźle", 82));
        lista.add(new Candidato("Aaron", "Gretna", 5));
        lista.add(new Candidato("Dara", "LaSalle", 81));
        lista.add(new Candidato("Christopher", "Pereira", 17));
        lista.add(new Candidato("Sheila", "Slough", 54));
        lista.add(new Candidato("Wayne", "Värnamo", 17));
        lista.add(new Candidato("Orson", "Beauwelz", 89));
        lista.add(new Candidato("Kalia", "Chilliwack", 17));
        lista.add(new Candidato("Buffy", "San Andrés", 13));
        lista.add(new Candidato("Tanisha", "Halle", 42));
        lista.add(new Candidato("Victoria", "Llanidloes", 19));
        lista.add(new Candidato("Shaeleigh", "Mold", 9));
        lista.add(new Candidato("Uta", "Pamplona", 87));
        lista.add(new Candidato("Brielle", "Killa Saifullah", 68));
        lista.add(new Candidato("Melinda", "Bollnäs", 77));
        lista.add(new Candidato("Noah", "Cardiff", 23));
        lista.add(new Candidato("Thomas", "Canoas", 74));
        lista.add(new Candidato("Branden", "Miami", 79));
        lista.add(new Candidato("Alvin", "Upper Hutt", 85));
        lista.add(new Candidato("Hollee", "Baltimore", 72));
        lista.add(new Candidato("Jordan", "Weston-super-Mare", 77));
        lista.add(new Candidato("Quinlan", "Halberstadt", 40));
        lista.add(new Candidato("Kelly", "Manchester", 17));
        lista.add(new Candidato("Cathleen", "Mussy-la-Ville", 52));
        lista.add(new Candidato("Xandra", "Kitscoty", 26));
        lista.add(new Candidato("Flavia", "Neerheylissem", 31));
        lista.add(new Candidato("Garrett", "Linz", 78));
        lista.add(new Candidato("Danielle", "Wandlitz", 31));
        lista.add(new Candidato("Carl", "Toledo", 40));
        lista.add(new Candidato("Brynne", "Porto Alegre", 34));
        lista.add(new Candidato("Abigail", "Coutisse", 7));
        lista.add(new Candidato("Abdul", "Amqui", 82));
        lista.add(new Candidato("Rigel", "Aurillac", 55));
        lista.add(new Candidato("Jocelyn", "Livorno", 55));
        lista.add(new Candidato("Merrill", "São João de Meriti", 70));
        lista.add(new Candidato("Clarke", "Ramara", 92));
        lista.add(new Candidato("Isabelle", "Drogenbos", 63));
        lista.add(new Candidato("Cleo", "Dunstable", 2));
        lista.add(new Candidato("Allistair", "Clovenfords", 85));
        lista.add(new Candidato("Kylan", "Garzón", 68));
    }

    public List<Candidato> getLista() {
        return lista;
    }
}
